### ISSUE TITLE
Exported file does not validate with 'Datev-Prüfprogramm' V.5.0

### ISSUE THREAD

**Issue by mseel** [ledermann/datev#1]
The headers did not match the datev pattern, shown in the picture below.

![datev_issue](https://cloud.githubusercontent.com/assets/2323440/18198394/109071b6-70fc-11e6-91a2-ba7ef9928edc.png)

I try to add the five missing headers and prepare a pull request.

**Comment by ledermann** [comment]
Thanks for reporting, @mseel. Currently, the output was checked against some third-party accounting software only.

I'm very interested in validating the output against the official DATEV software. I'm looking forward to your PR.

**Comment by ledermann** [comment]
Closed by #2
