### ISSUE TITLE
Datev::BookingExport (Versionsnummer/Formatversion)

### ISSUE THREAD

**Issue by sunsations** [ledermann/datev#13]
We are a happy user of your gem and are in the process for the DATEV "Buchungsstapel"-certification. 

The Feedback we got is:
- `Versionsnummer` must be `700` instead of `720`: https://github.com/ledermann/datev/blob/ac75ac0b0bbf6b8779ac502cc500eec66fb29372/lib/datev/base/header/booking_header.rb#L5
- `Formatversion` must be `9` to `7`: https://github.com/ledermann/datev/blob/ac75ac0b0bbf6b8779ac502cc500eec66fb29372/lib/datev/base/header/booking_header.rb#L8

Feedback in German:

_Die Versionsnummer (Feld 2) des Headers beträgt zur Zeit 700. Sie haben 720 aufgezeichnet. Diese Nummer ist ungültig.
Die Formatversion (Feld 5) ist beim Buchungsstapel 9, wenn der Header die Versionsnummer 700 hat._

It's possible to overwrite the defaults in the constructor like

```
    Datev::BookingExport.new(
      "Versionsnummer" => 700,
      "Formatversion" => 9,
      ....
    )
```

but I question, whether the defaults should be changed?

**Comment by ledermann** [comment]
Support for version 7.2 was added in #10. Since I'm currently not up to date on DATEV, I don't know if this matches the current release. Can you confirm that 700/9 ist the latest and greatest?

**Comment by sunsations** [comment]
I'm not the specialist in DATEV. All I can confirm is that I got the following answer

_Die Versionsnummer (Feld 2) des Headers beträgt zur Zeit 700. Sie haben 720 aufgezeichnet. Diese Nummer ist ungültig.

Die Formatversion (Feld 5) ist beim Buchungsstapel 9, wenn der Header die Versionsnummer 700 hat._

from DATEV-Schnittstellen-Beratung during the certification process. Thus, I have to rely on this information. 

As already mentioned, it's possible to overwrite it in order to not rely on the defaults (720/7).  Customers of us also have used exports with these default-settings without any problem. Thus, is see these change as optional and would probably close this issue until more users are complaining. What do you think?

**Comment by ledermann** [comment]
Okay, I think we can close this for now. If others confirm this as a bug, it can be fixed later. At the moment, overwriting in the constructor seems to to be ok for me.

**Comment by ledermann** [comment]
It seems that #17 fixes this, too
