### ISSUE TITLE
Invalid chars for Buchungsstapel "Belegfeld 1"

### ISSUE THREAD

**Issue by sunsations** [ledermann/datev#14]
Another feedback we got from the DATEV-review

_In den Belegfeldern sind folgende Zeichen zulässig:
Ziffern: 0 1 2...9
Großbuchstaben: A B C...Z
Kleinbuchstaben: a b c...z
Sonderzeichen: $ & % * + - /_

Do you think it would make sense to validate or sanitize the input in the gem directly?
My proposal would be to throw an exception if the input contains invalid chars and leave the sanitization (Umlaut-Replacement and the like) to the caller.

**Comment by ledermann** [comment]
I've just add an additional regex validation. What do you think?

**Comment by sunsations** [comment]
Saw your commit and I like it 👍. The same rule also applies for Belegfeld 2 according to the information I got from DATEV.

See PR:
https://github.com/ledermann/datev/pull/15/files

**Comment by ledermann** [comment]
Merged, thanks a lot for your help!
