### ISSUE TITLE
Default header attribute for "Erzeugt am" is not evaluated at runtime

### ISSUE THREAD

**Issue by JohannaHartmann** [ledermann/datev#18]
The classes `Datev::AccountHeader`,  `Datev::BookingHeader` and  `Datev::ContactHeader` use `Time.now.utc` for `Erzeugt am`. I suggest that the timestamp is evaluated at runtime and not when evaluating the class. Otherwise it uses the timestamp when the server starts and not when generating the export.

You can fix this with a proc in each subclass of `Header`, for example:
```
self.default_attributes = proc do
    { ... }
end
```

And in the `Datev::Base` class the code below could be used to prevent breaking existing code:
```
attr_writer :default_attributes

def default_attributes
  if @default_attributes.is_a?(Proc)
    @default_attributes.call
  else
    @default_attributes
  end
end
```

What do you think?

**Comment by ledermann** [comment]
@JohannaHartmann You are absolutely right, evaluating `Time.now` at class loading time is not useful. I have taken your proposal and created a new release. Thanks a lot!
