### ISSUE TITLE
Datev Format expects quoting for string fields 

### ISSUE THREAD

**Issue by mseel** [ledermann/datev#3]
According to Datev Spec V.5.0 
- values of type text must be quoted in the output csv 
- if they do not contain a value - quotes must be present
- if the value of a text column contains a double quote it must be doubled

**Comment by JGantner** [comment]
This seems to be tricky. Had a quick look at the CSV-Library. Quoting values before sending them to CSV triggers the CSV quoting rules which result in incorrect output. Not sure how to tackle this problem.

**Comment by ledermann** [comment]
It seems we need to patch/subclass the `CSV` class to achieve this:
http://stackoverflow.com/questions/4854900/how-do-i-force-one-field-in-rubys-csv-output-to-be-wrapped-with-double-quotes

I will try it later.

**Comment by ralfebert** [comment]
I just had the same problem, to get the exact same output as an example file from DATEV, including some quirks like slightly different field names, I created a fork (simplified - only bookings) that does the CSV generation manually: https://github.com/ralfebert/datev

**Comment by ledermann** [comment]
You are right, @ralfebert, building the CSV the manual way seems to be a much simpler approach.

**Comment by ledermann** [comment]
Closed by 974593b5d1f76f0801f17f898ca4bc1dec0aa121
